import { test, expect, _electron as electron } from '@playwright/test';
import path from 'node:path';
import { mkdir, readFile } from 'node:fs/promises';

test('desktop workflow, semantic retrieval, and durable Markdown history', async () => {
  const directory = path.resolve(`.test-data/desktop-${Date.now()}`);
  await mkdir(directory, { recursive: true });
  const app = await electron.launch({ args: ['.'], env: { ...process.env, OINTEL_DATA_DIR: directory, OINTEL_MODEL_CACHE: path.resolve('.test-data/vectors/models'), OINTEL_TEST_MODE: '1' } });
  const page = await app.firstWindow();
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    await expect(page.getByLabel('Map title')).toHaveValue('A space for connected thinking');
    await expect(page.locator('.react-flow__node')).toHaveCount(6);
    await expect(page.locator('.react-flow__edge-path')).toHaveCount(5);
    await expect(page.locator('.inspector .markdown h1')).toHaveText('A more connected mind');
    await page.screenshot({ path: 'artifacts/ointel-desktop.png' });
    await page.locator('.react-flow__edge-interaction').first().click({ force: true });
    await expect(page.locator('.edge-intro')).toContainText('A thread between ideas');
    await page.getByLabel('Path', { exact: true }).selectOption('angular');
    await page.getByLabel('Line style', { exact: true }).selectOption('dashed');
    await page.getByLabel('Target terminator', { exact: true }).selectOption('solid-arrow');
    await page.locator('.idea-list-item').filter({ hasText: 'A more connected mind' }).click();
    await page.getByRole('button', { name: 'Pin node', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Unpin node', exact: true })).toBeVisible();
    const position = await page.evaluate(async () => (await window.ointel!.load())?.nodes.find(n => n.id === 'start')?.position);
    await page.getByRole('button', { name: 'Choose arrangement' }).click();
    await page.getByRole('button', { name: /Hierarchy A clear/ }).click();
    await expect(page.locator('.save-indicator')).toHaveText('All changes saved');
    expect(await page.evaluate(async () => (await window.ointel!.load())?.nodes.find(n => n.id === 'start')?.position)).toEqual(position);
    await page.getByRole('button', { name: 'Style', exact: true }).click();
    await page.getByRole('button', { name: 'Lavender palette' }).click();
    await page.getByLabel('Border width', { exact: true }).fill('3');
    await expect(page.locator('[data-id="start"] .idea-card')).toHaveAttribute('style', /border-width: 3px/);
    await page.getByRole('button', { name: 'Note', exact: true }).click();
    await page.getByRole('button', { name: 'Edit on card', exact: true }).click();
    await page.getByLabel('Node title').fill('Urban gardening');
    await page.getByRole('textbox', { name: 'Card note' }).fill('');
    await page.getByRole('textbox', { name: 'Card note' }).evaluate(element => {
      const data = new DataTransfer(); data.setData('text/plain', '## Grow your own food\n\nTomatoes and herbs thrive in pots on a sunny balcony. Compost enriches the soil.\n\n[Research](node://research)');
      element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }));
    });
    await page.locator('.inline-edit-footer').getByRole('button', { name: 'Save version', exact: true }).click();
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await expect(page.locator('.inspector .markdown h2')).toHaveText('Grow your own food');
    await page.locator('.inspector').getByRole('link', { name: 'Research' }).click();
    await expect(page.getByLabel('Node title')).toHaveValue('Follow your curiosity');
    await page.locator('.idea-list-item').filter({ hasText: 'Urban gardening' }).click();
    await page.getByRole('button', { name: /History/ }).click();
    await expect(page.locator('.history-nav')).toContainText('Version 2 of 2');
    await page.getByRole('button', { name: 'Previous version' }).click();
    await expect(page.locator('.version-preview')).toContainText('A more connected mind');
    await page.getByRole('button', { name: 'Restore this version' }).click();
    await expect(page.getByLabel('Node title')).toHaveValue('A more connected mind');
    await page.getByRole('button', { name: 'Next version' }).click();
    await page.getByRole('button', { name: 'Restore this version' }).click();
    await expect(page.getByLabel('Node title')).toHaveValue('Urban gardening');
    await page.getByRole('button', { name: 'Note', exact: true }).click();
    await page.getByRole('button', { name: 'Edit on card', exact: true }).click();
    await page.getByRole('textbox', { name: 'Card note' }).focus();
    await page.getByRole('textbox', { name: 'Card note' }).press('Control+End');
    await page.getByRole('textbox', { name: 'Card note' }).evaluate(element => {
      const data = new DataTransfer();
      const bytes = Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZQAAAABJRU5ErkJggg=='), c => c.charCodeAt(0));
      data.items.add(new File([bytes], 'screenshot.png', { type: 'image/png' }));
      element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }));
    });
    await expect(page.getByRole('textbox', { name: 'Card note' }).locator('img')).toHaveCount(1);
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await expect(page.locator('.inspector').getByRole('img', { name: 'screenshot.png' })).toBeVisible();
    await page.getByRole('button', { name: /Search your thoughts/ }).click();
    await page.getByRole('textbox', { name: 'Search thoughts' }).fill('How can I raise food on my apartment terrace?');
    await expect(page.locator('.search-result').first()).toContainText('Urban gardening', { timeout: 90000 });
    await page.screenshot({ path: 'artifacts/ointel-vector-search.png' });
    await page.locator('.search-result').first().click();
    await expect(page.getByLabel('Node title')).toHaveValue('Urban gardening');
    await page.getByRole('button', { name: 'Add connected idea' }).click();
    await expect(page.locator('.react-flow__node')).toHaveCount(7);
    await page.getByLabel('Node title').fill('A new branch');
    await page.getByRole('button', { name: 'Delete idea', exact: true }).click();
    await expect(page.locator('.react-flow__node')).toHaveCount(6);
    await page.getByRole('button', { name: 'Undo', exact: true }).click();
    await expect(page.locator('.react-flow__node')).toHaveCount(7);
    await page.getByRole('button', { name: 'Redo', exact: true }).click();
    await expect(page.locator('.react-flow__node')).toHaveCount(6);
    await expect(page.locator('.save-indicator')).toHaveText('All changes saved');
    const saved = JSON.parse(await readFile(path.join(directory, 'workspace.json'), 'utf8'));
    expect(saved.nodes[0].history.length).toBeGreaterThanOrEqual(4);
    expect(await readFile(path.join(directory, 'notes/start.md'), 'utf8')).toContain('assets/');
    await page.reload();
    await expect(page.getByLabel('Node title')).toHaveValue('Urban gardening');
    expect(errors).toEqual([]);
  } finally { await app.evaluate(({ app }) => app.exit()); }
});
