import { test, expect, _electron as electron } from '@playwright/test';
import path from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';
import { initialWorkspace } from '../../src/lib/model';

test('groups move, reshape, style, persist, and ungroup without losing cards', async () => {
  const directory = path.resolve(`.test-data/groups-${Date.now()}`), workspace = initialWorkspace();
  workspace.nodes = workspace.nodes.slice(0, 3); workspace.nodes.forEach((n, i) => { n.position = { x: i * 330, y: i === 1 ? 170 : 0 }; });
  workspace.edges = workspace.edges.filter(e => workspace.nodes.some(n => n.id === e.source) && workspace.nodes.some(n => n.id === e.target));
  await mkdir(directory, { recursive: true }); await writeFile(path.join(directory, 'workspace.json'), JSON.stringify(workspace));
  const app = await electron.launch({ args: ['.'], env: { ...process.env, OINTEL_DATA_DIR: directory, OINTEL_MODEL_CACHE: path.resolve('.test-data/vectors/models'), OINTEL_TEST_MODE: '1' } });
  const page = await app.firstWindow(), errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await app.evaluate(({ BrowserWindow }) => { const win = BrowserWindow.getAllWindows()[0]; win.setOpacity(0); win.setSkipTaskbar(true); win.webContents.setBackgroundThrottling(false); win.showInactive(); });
  const save = () => page.evaluate(async () => (await window.ointel!.load())!);
  const card = (i: number) => page.locator(`.react-flow__node[data-id="${workspace.nodes[i].id}"]`);
  const boundary = page.locator('.group-boundary');
  try {
    await expect(card(0)).toBeVisible();
    await card(0).click(); await page.keyboard.down(process.platform === 'darwin' ? 'Meta' : 'Control'); await card(1).click(); await page.keyboard.up(process.platform === 'darwin' ? 'Meta' : 'Control');
    await page.getByRole('button', { name: 'Group selected', exact: true }).click();
    await expect(page.getByLabel('Group details', { exact: true })).toBeVisible();
    await expect(boundary).toHaveCount(1);
    await page.getByLabel('Group name', { exact: true }).fill('Product discovery'); await page.getByLabel('Group name', { exact: true }).press('Enter');
    await page.getByLabel('Region background', { exact: true }).fill('#dce5f5');
    await page.getByLabel('Region border color', { exact: true }).fill('#7e97ba');
    await page.getByLabel('Region border style', { exact: true }).selectOption('dashed');
    await page.getByRole('switch', { name: 'Region drop shadow' }).click();
    await page.getByLabel('Boundary padding', { exact: true }).fill('44');
    await page.getByLabel('Boundary softness', { exact: true }).fill('1');
    await page.getByLabel('Fill opacity', { exact: true }).fill('0.4');
    await expect(boundary).toHaveAttribute('fill', '#dce5f5'); await expect(boundary).toHaveAttribute('stroke-dasharray', '10 7');
    await expect.poll(async () => (await save()).groups[0]?.name).toBe('Product discovery');
    const before = (await save()).nodes.map(n => n.position), label = page.getByRole('button', { name: 'Select group Product discovery', exact: true });
    const box = (await label.boundingBox())!;
    await page.mouse.move(box.x + 35, box.y + 12); await page.mouse.down(); await page.mouse.move(box.x + 95, box.y + 62, { steps: 12 }); await page.mouse.up();
    await expect.poll(async () => (await save()).nodes[0].position.x).toBeGreaterThan(before[0].x + 20);
    const moved = (await save()).nodes.map(n => n.position);
    expect(moved[1].x - before[1].x).toBeCloseTo(moved[0].x - before[0].x); expect(moved[1].y - before[1].y).toBeCloseTo(moved[0].y - before[0].y); expect(moved[2]).toEqual(before[2]);
    await page.getByRole('button', { name: 'Undo', exact: true }).click(); await expect.poll(async () => (await save()).nodes.map(n => n.position)).toEqual(before);
    await page.getByRole('button', { name: 'Redo', exact: true }).click(); await expect.poll(async () => (await save()).nodes.map(n => n.position)).toEqual(moved);
    await card(0).click();
    const resizePath = await boundary.getAttribute('d'), handle = (await card(0).locator('.card-resize-handle.bottom.right').boundingBox())!;
    await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2); await page.mouse.down(); await page.mouse.move(handle.x + handle.width / 2 + 40, handle.y + handle.height / 2 + 25, { steps: 8 }); await page.mouse.up();
    await expect(boundary).not.toHaveAttribute('d', resizePath!);
    await expect.poll(async () => (await save()).nodes[0].size?.width || 240).toBeGreaterThan(240);
    await page.getByLabel('Select card group', { exact: true }).selectOption({ label: 'Product discovery (2)' });
    const oldPath = await boundary.getAttribute('d'); await card(1).getByRole('button', { name: 'Collapse card', exact: true }).click(); await expect(boundary).not.toHaveAttribute('d', oldPath!);
    // Every member corner remains inside the smoothed region.
    expect(await page.evaluate(() => { const p = document.querySelector('.group-boundary') as SVGGeometryElement; const svg = p.ownerSVGElement!;
      return Array.from(document.querySelectorAll('.react-flow__node.selected')).every(n => { const r = n.getBoundingClientRect(); return [[r.left, r.top], [r.right, r.top], [r.left, r.bottom], [r.right, r.bottom]].every(([x, y]) => { const q = svg.createSVGPoint(); q.x = x; q.y = y; return p.isPointInFill(q.matrixTransform(p.getScreenCTM()!.inverse())); }); });
    })).toBe(true);
    await expect.poll(async () => (await save()).nodes[1].collapsed).toBe(true);
    await page.reload(); await expect(boundary).toHaveAttribute('fill', '#dce5f5');
    await page.getByLabel('Select card group', { exact: true }).selectOption({ label: 'Product discovery (2)' });
    await expect(page.getByRole('switch', { name: 'Region drop shadow' })).toHaveAttribute('aria-checked', 'true');
    // Pinning a member fixes the whole group during boundary dragging and layout.
    await card(0).click(); await page.getByRole('button', { name: 'Pin position', exact: true }).click();
    await page.getByLabel('Select card group', { exact: true }).selectOption({ label: 'Product discovery (2)' });
    const pinned = (await save()).nodes.map(n => n.position), lockedLabel = (await label.boundingBox())!;
    await page.mouse.move(lockedLabel.x + 30, lockedLabel.y + 10); await page.mouse.down(); await page.mouse.move(lockedLabel.x + 80, lockedLabel.y + 50, { steps: 8 }); await page.mouse.up();
    await page.getByRole('button', { name: 'Auto-arrange', exact: true }).click();
    await expect.poll(async () => (await save()).nodes.slice(0, 2).map(n => n.position)).toEqual(pinned.slice(0, 2));
    await page.getByRole('button', { name: 'Fit all ideas', exact: true }).click(); await page.waitForTimeout(550);
    await page.screenshot({ path: 'artifacts/ointel-groups.png' });
    await page.getByRole('button', { name: 'Ungroup cards', exact: true }).click(); await expect(boundary).toHaveCount(0);
    await expect.poll(async () => (await save()).groups.length).toBe(0); expect((await save()).nodes.length).toBe(3); expect((await save()).edges).toEqual(workspace.edges);
    await page.getByRole('button', { name: 'Undo', exact: true }).click(); await expect(boundary).toHaveCount(1);
    // Removing every member also removes the empty region. Undo restores membership.
    await page.getByLabel('Select card group', { exact: true }).selectOption({ label: 'Product discovery (2)' });
    await page.getByRole('button', { name: `Remove ${workspace.nodes[0].title} from group`, exact: true }).click();
    await page.getByRole('button', { name: `Remove ${workspace.nodes[1].title} from group`, exact: true }).click(); await expect(boundary).toHaveCount(0);
    await page.getByRole('button', { name: 'Undo', exact: true }).click(); await expect(boundary).toHaveCount(1);
    await page.getByLabel('Select card group', { exact: true }).selectOption({ label: 'Product discovery (1)' });
    await page.getByLabel('Add card to group', { exact: true }).selectOption(workspace.nodes[2].id);
    await expect.poll(async () => (await save()).groups[0]?.nodeIds).toEqual([workspace.nodes[1].id, workspace.nodes[2].id]);
    await page.getByRole('button', { name: 'Undo', exact: true }).click();
    await expect(page.locator('.react-flow__node.selected')).toHaveCount(1);
    await page.getByLabel('Select card group', { exact: true }).selectOption({ label: 'Product discovery (1)' });
    await card(1).click({ button: 'right' }); await page.getByRole('menuitem', { name: 'Delete node', exact: true }).click();
    await expect(boundary).toHaveCount(0); await expect.poll(async () => (await save()).nodes.length).toBe(2);
    await page.getByRole('button', { name: 'Undo', exact: true }).click(); await expect(boundary).toHaveCount(1);
    await page.getByRole('button', { name: 'Select all cards', exact: true }).click();
    await page.keyboard.press(process.platform === 'darwin' ? 'Meta+g' : 'Control+g');
    await expect.poll(async () => (await save()).groups.at(-1)?.nodeIds.length).toBe(3);
    await page.keyboard.press(process.platform === 'darwin' ? 'Meta+Shift+g' : 'Control+Shift+g');
    await expect(boundary).toHaveCount(1); await expect.poll(async () => (await save()).nodes.length).toBe(3);
    expect(errors).toEqual([]);
  } finally { await app.evaluate(({ app }) => app.exit()); }
});
