import { test, expect, _electron as electron } from '@playwright/test';
import path from 'node:path';
import { readFile } from 'node:fs/promises';

test('inline note formatting targets selections and the caret, with durable Markdown', async () => {
  const directory = path.resolve(`.test-data/inline-${Date.now()}`);
  const app = await electron.launch({ args: ['.'], env: { ...process.env, OINTEL_DATA_DIR: directory, OINTEL_MODEL_CACHE: path.resolve('.test-data/vectors/models'), OINTEL_TEST_MODE: '1' } });
  const page = await app.firstWindow();
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    await expect(page.getByLabel('Map title')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Bold note text' })).toBeDisabled();
    await page.locator('[data-id="start"] .idea-eyebrow').dblclick();
    const note = page.getByRole('textbox', { name: 'Card note' });
    await expect(note).toBeVisible();
    await note.press('Control+End');
    await page.keyboard.type('Hello world');
    await expect(note).toContainText('Hello world');
    await expect(page.locator('.inspector [contenteditable]')).toHaveCount(0);
    await page.getByLabel('Card title').fill('Formatting experiment');
    await note.fill('Alpha beta gamma');
    await note.press('Control+Home');
    for (let i = 0; i < 6; i++) await note.press('ArrowRight');
    for (let i = 0; i < 4; i++) await note.press('Shift+ArrowRight');
    await expect.poll(() => page.evaluate(() => window.getSelection()?.toString())).toBe('beta');
    await page.getByRole('button', { name: 'Bold note text' }).click();
    await expect(note.locator('strong')).toHaveText('beta');
    await page.getByLabel('Note font', { exact: true }).selectOption('Georgia');
    await page.getByLabel('Note font size').selectOption('24px');
    await page.getByLabel('Note text color').fill('#aa2233');
    await page.getByRole('button', { name: 'Underline note text' }).click();
    await page.getByRole('button', { name: 'Insert node link' }).click();
    await page.locator('.toolbar-link-picker').getByRole('button', { name: 'Follow your curiosity', exact: true }).click();
    await expect(note.locator('span').filter({ hasText: /^beta$/ })).toHaveCSS('color', 'rgb(170, 34, 51)');
    await expect(note.locator('span').filter({ hasText: /^beta$/ })).toHaveCSS('font-family', 'Georgia');
    await note.press('Control+End');
    await page.getByRole('button', { name: 'Italic note text' }).click();
    await page.keyboard.type('delta');
    await expect(note.locator('em')).toHaveText('delta');
    await expect(note.locator('strong')).toHaveText('beta');
    await expect(note.locator('u')).toHaveText('beta');
    await page.getByRole('button', { name: 'Style', exact: true }).click();
    await page.getByRole('button', { name: 'Lavender palette' }).click();
    await page.getByLabel('Border width', { exact: true }).fill('3');
    await expect(note.locator('strong')).toHaveText('beta');
    await page.locator('.inline-edit-footer').getByRole('button', { name: 'Save version' }).click();
    await page.screenshot({ path: 'artifacts/ointel-inline-editing.png' });
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await expect(note).toHaveCount(0);
    await page.getByRole('button', { name: 'Note', exact: true }).click();
    const preview = page.locator('.inspector .markdown');
    await expect(preview.locator('strong')).toHaveText('beta');
    await expect(preview.locator('span').filter({ hasText: /^beta$/ })).toHaveCSS('font-size', '24px');
    await expect(page.locator('.save-indicator')).toHaveText('All changes saved');
    const saved = JSON.parse(await readFile(path.join(directory, 'workspace.json'), 'utf8'));
    expect(saved.nodes[0].title).toBe('Formatting experiment');
    expect(saved.nodes[0].body).toContain('<span style=');
    expect(saved.nodes[0].body).toContain('beta');
    expect(saved.nodes[0].history).toHaveLength(2);
    await page.reload();
    await page.locator('[data-id="start"] .idea-eyebrow').dblclick();
    await expect(note.locator('strong')).toHaveText('beta');
    await expect(note.locator('em')).toHaveText('delta');
    await expect(note.locator('span').filter({ hasText: /^beta$/ })).toHaveCSS('color', 'rgb(170, 34, 51)');
    await expect(note.locator('u')).toHaveText('beta');
    await expect(note.locator('a')).toHaveText('beta');
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await page.getByRole('button', { name: /History/ }).click();
    await page.getByRole('button', { name: 'Previous version' }).click();
    await page.getByRole('button', { name: 'Restore this version' }).click();
    await expect(page.getByLabel('Node title')).toHaveValue('A more connected mind');
    await page.getByRole('button', { name: 'Next version' }).click();
    await page.getByRole('button', { name: 'Restore this version' }).click();
    await page.locator('[data-id="start"] .idea-eyebrow').dblclick();
    await expect(note.locator('strong')).toHaveText('beta');
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await page.getByRole('button', { name: 'Note', exact: true }).click();
    await preview.getByRole('link', { name: 'beta' }).click();
    await expect(page.getByLabel('Node title')).toHaveValue('Follow your curiosity');
    expect(errors).toEqual([]);
  } finally { await app.evaluate(({ app }) => app.exit()); }
});
