import { test, expect, _electron as electron } from '@playwright/test';
import path from 'node:path';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { initialWorkspace } from '../../src/lib/model';

test('multi-selection, full theme application, editor, persistence and undo', async () => {
  const directory = path.resolve(`.test-data/themes-${Date.now()}`);
  const app = await electron.launch({ args: ['.'], env: { ...process.env, OINTEL_DATA_DIR: directory, OINTEL_MODEL_CACHE: path.resolve('.test-data/vectors/models'), OINTEL_TEST_MODE: '1' } });
  const page = await app.firstWindow();
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  try {
    await expect(page.getByLabel('Map title')).toBeVisible();
    const count = page.locator('.selected-card-count');
    await expect(count).toHaveText('1 selected');
    await page.locator('[data-id="research"] .idea-eyebrow').click({ modifiers: ['Control'] });
    await expect(count).toHaveText('2 selected');
    await expect(page.locator('.react-flow__node.selected')).toHaveCount(2);
    await page.getByRole('button', { name: 'Apply Blueprint theme', exact: true }).click();
    for (const id of ['start', 'research']) {
      await expect(page.locator(`[data-id="${id}"] .idea-card`)).toHaveCSS('border-style', 'dashed');
      await expect(page.locator(`[data-id="${id}"] .idea-title`)).toHaveClass(/font-mono/);
    }
    await expect(page.locator('[data-id="ideas"] .idea-card')).toHaveCSS('border-style', 'solid');
    await page.getByRole('button', { name: 'Undo', exact: true }).click();
    await expect(page.locator('[data-id="start"] .idea-card')).toHaveCSS('border-style', 'solid');
    await expect(page.locator('[data-id="research"] .idea-card')).toHaveCSS('border-style', 'solid');
    await page.getByRole('button', { name: 'Redo', exact: true }).click();
    await expect(count).toHaveText('2 selected');
    await page.getByRole('button', { name: 'Theme editor', exact: true }).click();
    const editor = page.getByRole('dialog', { name: 'Theme editor', exact: true });
    await editor.getByLabel('Theme name', { exact: true }).fill('Evening notes');
    await editor.getByLabel('Background', { exact: true }).fill('#eee4ff');
    await editor.getByLabel('Border style', { exact: true }).selectOption('dotted');
    await editor.getByLabel('Border width', { exact: true }).fill('3');
    await editor.getByLabel('Font family', { exact: true }).selectOption('serif');
    await editor.getByLabel('Font size', { exact: true }).fill('20');
    await editor.getByLabel('Corner radius', { exact: true }).fill('24');
    await editor.getByRole('button', { name: 'Italic title', exact: true }).click();
    await expect(editor.getByTestId('theme-preview')).toHaveCSS('border-style', 'dotted');
    await expect(page.locator('[data-id="start"] .idea-card')).toHaveCSS('border-style', 'dashed');
    await page.screenshot({ path: 'artifacts/ointel-theme-editor.png' });
    await editor.getByRole('button', { name: 'Save and apply to 2 cards', exact: true }).click();
    await expect(editor).toHaveCount(0);
    await expect(page.getByRole('button', { name: 'Apply Evening notes theme', exact: true })).toHaveAttribute('aria-pressed', 'true');
    for (const id of ['start', 'research']) await expect(page.locator(`[data-id="${id}"] .idea-card`)).toHaveCSS('border-style', 'dotted');
    await page.locator('[data-id="research"] .idea-eyebrow').click({ modifiers: ['Control'] });
    await expect(count).toHaveText('1 selected');
    await expect(page.getByLabel('Node title', { exact: true })).toHaveValue('A more connected mind');
    await page.getByRole('button', { name: 'Clear card selection', exact: true }).click();
    await expect(count).toHaveText('0 selected');
    await expect(page.getByRole('button', { name: 'Apply Sage theme', exact: true })).toBeDisabled();
    const canvas = await page.getByTestId('canvas').boundingBox();
    if (!canvas) throw new Error('No canvas');
    await page.keyboard.down('Shift');
    await page.mouse.move(canvas.x + 8, canvas.y + 8); await page.mouse.down();
    await page.mouse.move(canvas.x + canvas.width - 12, canvas.y + canvas.height - 12, { steps: 20 }); await page.mouse.up();
    await page.keyboard.up('Shift');
    await expect(count).toHaveText('6 selected');
    expect(await page.evaluate(() => window.getSelection()?.toString())).toBe('');
    await page.getByRole('button', { name: 'Apply Editorial theme', exact: true }).click();
    await expect(page.locator('.idea-title.font-serif')).toHaveCount(6);
    await page.getByRole('button', { name: 'Undo', exact: true }).click();
    await page.getByRole('button', { name: 'Clear card selection', exact: true }).click();
    await page.getByRole('button', { name: 'Select all cards', exact: true }).click();
    await expect(count).toHaveText('6 selected');
    await page.screenshot({ path: 'artifacts/ointel-multi-select.png' });
    await expect(page.locator('.save-indicator')).toHaveText('All changes saved');
    await expect.poll(async () => JSON.parse(await readFile(path.join(directory, 'workspace.json'), 'utf8')).customThemes.length).toBe(1);
    const saved = JSON.parse(await readFile(path.join(directory, 'workspace.json'), 'utf8'));
    expect(saved.nodes[0].style).toEqual(saved.customThemes[0].style);
    expect(saved.nodes[1].style).toEqual(saved.customThemes[0].style);
    await page.reload();
    await expect(page.getByRole('button', { name: 'Apply Evening notes theme', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Theme editor', exact: true }).click();
    await editor.getByLabel('Theme to edit', { exact: true }).selectOption(saved.customThemes[0].id);
    await expect(editor.getByLabel('Theme name', { exact: true })).toHaveValue('Evening notes');
    await editor.getByLabel('Theme name', { exact: true }).fill('Evening edited');
    await editor.getByRole('button', { name: 'Save theme', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Apply Evening edited theme', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Theme editor', exact: true }).click();
    await editor.getByLabel('Theme to edit', { exact: true }).selectOption(saved.customThemes[0].id);
    await editor.getByRole('button', { name: 'Duplicate theme', exact: true }).click();
    await editor.getByRole('button', { name: 'Save theme', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Apply Evening edited copy theme', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Theme editor', exact: true }).click();
    await editor.getByLabel('Theme to edit', { exact: true }).selectOption({ label: 'Evening edited copy' });
    await editor.getByRole('button', { name: 'Delete theme', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Apply Evening edited copy theme', exact: true })).toHaveCount(0);
    await expect(page.locator('[data-id="start"] .idea-card')).toHaveCSS('border-style', 'dotted');
    expect(errors).toEqual([]);
  } finally { await app.evaluate(({ app }) => app.exit()); }
});

test('group movement preserves pinned cards; group deletion and movement undo atomically', async () => {
  const directory = path.resolve(`.test-data/group-movement-${Date.now()}`);
  const workspace = initialWorkspace(); workspace.nodes[0].locked = true;
  await mkdir(directory, { recursive: true });
  await writeFile(path.join(directory, 'workspace.json'), JSON.stringify(workspace));
  const app = await electron.launch({ args: ['.'], env: { ...process.env, OINTEL_DATA_DIR: directory, OINTEL_MODEL_CACHE: path.resolve('.test-data/vectors/models'), OINTEL_TEST_MODE: '1' } });
  const page = await app.firstWindow();
  const snapshot = async () => JSON.parse(await readFile(path.join(directory, 'workspace.json'), 'utf8')) as typeof workspace;
  const position = async (id: string) => (await snapshot()).nodes.find(node => node.id === id)!.position;
  try {
    await expect(page.getByLabel('Map title')).toBeVisible();
    for (const id of ['research', 'notes']) await page.locator(`[data-id="${id}"] .idea-eyebrow`).click({ modifiers: ['Control'] });
    await expect(page.locator('.selected-card-count')).toHaveText('3 selected');
    const card = await page.locator('[data-id="research"] .idea-eyebrow').boundingBox();
    if (!card) throw new Error('No card');
    await page.mouse.move(card.x + 25, card.y + 5); await page.mouse.down();
    await page.mouse.move(card.x + 100, card.y + 45, { steps: 15 }); await page.mouse.up();
    await expect.poll(() => position('research')).not.toEqual(workspace.nodes[1].position);
    const moved = await snapshot();
    const delta = { x: moved.nodes[1].position.x - workspace.nodes[1].position.x, y: moved.nodes[1].position.y - workspace.nodes[1].position.y };
    expect(moved.nodes[3].position.x - workspace.nodes[3].position.x).toBeCloseTo(delta.x);
    expect(moved.nodes[3].position.y - workspace.nodes[3].position.y).toBeCloseTo(delta.y);
    expect(moved.nodes[0].position).toEqual(workspace.nodes[0].position);
    expect(moved.nodes[2].position).toEqual(workspace.nodes[2].position);
    await page.getByRole('button', { name: 'Undo', exact: true }).click();
    await expect.poll(async () => (await snapshot()).nodes.map(node => node.position)).toEqual(workspace.nodes.map(node => node.position));
    await page.keyboard.press('Delete');
    await expect(page.locator('.idea-card')).toHaveCount(3);
    await expect(page.locator('.react-flow__edge')).toHaveCount(0);
    await page.getByRole('button', { name: 'Undo', exact: true }).click();
    await expect(page.locator('.idea-card')).toHaveCount(6);
    await expect(page.locator('.react-flow__edge')).toHaveCount(5);
    await page.keyboard.press('Control+a');
    await expect(page.locator('.selected-card-count')).toHaveText('6 selected');
    await page.locator('[data-id="research"] .idea-eyebrow').click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Pin selected cards', exact: true }).click();
    await expect(page.getByLabel('Pinned', { exact: true })).toHaveCount(6);
    await page.getByRole('button', { name: 'Unpin selected', exact: true }).click();
    await expect(page.getByLabel('Pinned', { exact: true })).toHaveCount(0);
  } finally { await app.evaluate(({ app }) => app.exit()); }
});
